version: '3.9'

services:
  vscode:
    build: 
      context: ./
      dockerfile: ./Dockerfile.dev
    command: /bin/bash -c "while sleep 1000; do :; done"
    working_dir: /server
    networks:
      - app-network
    volumes:
      # Nous allons préciser le dossier local
      - .:/server:cached

  dbms:
    image: mariadb
    restart: always
    ports:
      - "3315:3306"
    env_file: 
      - ./dbms/.env.dev
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    volumes:
      - ./dbms/dbms-data:/var/lib/mysql
      - ./dbms/mariadb.cnf:/etc/mysql/mariadb.cnf
      # Pointer vers le fichier de configuration pour la base de dev
      - ./dbms/dev-initdb.d/001-init-dev.sql:/docker-entrypoint-initdb.d/001-init-dev.sql
      # Pointer vers le fichier de configuration pour la base de test
      # - ./dbms/test-initdb.d/001-init-test.sql:/docker-entrypoint-initdb.d/002-init-test.sql
      # Ajouter le DDL qui va tourner en dernier
      - ./dbms/ddl/ddl.sql:/docker-entrypoint-initdb.d/099-ddl.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
